### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: Microsoft.Quantum.Environment
summary: >-
  Retourne le nombre de qubits actuellement disponibles pour emprunter.

  Cela comprend les qubits inutilisés ; autrement dit, cela comprend les qubits retournés par `GetQubitsAvailableToUse`.
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Nombre de qubits qui peuvent être alloués dans une instruction `borrowing`.

      Si l’ordinateur cible utilisé ne fournit pas ces informations, `-1` est retourné.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
metadata:
  ms.openlocfilehash: c0caf866ad9a8773aa11ee7c6951ca3acc60cbaa
  ms.sourcegitcommit: edcf15044d7bdf4f8b21fb8f6af4bde475eb13a0
  ms.translationtype: MT
  ms.contentlocale: fr-FR
  ms.lasthandoff: 11/05/2019
  ms.locfileid: "73230481"
