### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft.Quantum.Environment
summary: " # <a name=\"summary\"></a>Résumé\n Ces fonctions fournissent des informations sur l’environnement dans lequel le calcul de Quantum se produit."
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    Retourne le nombre de qubits actuellement disponibles pour emprunter.

    Cela comprend les qubits inutilisés ; autrement dit, cela comprend le qubits retourné par `GetQubitsAvailableToUse`.
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: Retourne le nombre de qubits actuellement disponibles à utiliser.
metadata:
  ms.openlocfilehash: bd6d442aabb179f4c5fea0a0f48efaa472ec00cf
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: fr-FR
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82673345"
