### YamlMime:QSharpNamespace
functions: []
name: Microsoft.Quantum.Environment
newtypes: []
operations:
- summary: Retourne le nombre de qubits actuellement disponibles pour emprunter.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToBorrow
- summary: Retourne le nombre de qubits actuellement disponibles à utiliser.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToUse
summary: Ces fonctions fournissent des informations sur l’environnement dans lequel le calcul de Quantum se produit.
uid: Microsoft.Quantum.Environment
metadata:
  ms.openlocfilehash: 87e1659f8ecdd6df99271f7552f683ffed85b151
  ms.sourcegitcommit: a87c1aa8e7453360025e47ba614f25b02ea84ec3
  ms.translationtype: MT
  ms.contentlocale: fr-FR
  ms.lasthandoff: 11/26/2020
  ms.locfileid: "96201442"
