### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: microsoft.quantum.environment
summary: >-
  Retourne le nombre de qubits actuellement disponibles pour emprunter.

  Cela comprend les qubits inutilisés ; autrement dit, cela comprend le qubits retourné par `GetQubitsAvailableToUse` .
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Nombre de qubits qui peuvent être alloués dans une `borrowing` instruction.

      Si l’ordinateur cible utilisé ne fournit pas ces informations, `-1` est retourné.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
metadata:
  ms.openlocfilehash: 18e68548e9f344a70dac95f70528a8b3e87f5909
  ms.sourcegitcommit: 685a8ab16d7e6a25e63a168d6e7c385fa6e876cc
  ms.translationtype: MT
  ms.contentlocale: fr-FR
  ms.lasthandoff: 09/29/2020
  ms.locfileid: "91478067"
